; PlatformIO Project Configuration File
;
[platformio]
name = git config --global http.postBuffer 157286400
default_envs = esp32doit-devkit-v1

[env:esp32doit-devkit-v1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = esp32-s3-devkitm-1

;board_build.partitions = partitions_custom.csv
;     board_build.partitions = no_ota.csv
;; otherwise will exceed memory limit
;; min_spiffs (1.9MB APP with OTA/190KB SPIFFS)
;; minimal    (1.3MB APP/700KB SPIFFS)
board_build.partitions = min_spiffs.csv
board_build.filesystem = littlefs

; esptool - get port+device   esptool.py flash_id
; esptool - erase flash       esptool.py --port /dev/cu.usbserial-02220C7B erase_flash

upload_port     = /dev/cu.wchusbserial10
upload_speed    = 921600  ; 921600, 512000, 460800, 256000, 115200

;upload_protocol = espota
;upload_port = 192.168.148.144
;upload_port = IP_ADDRESS_HERE or mDNS_NAME.local

monitor_speed   = 115200  ; 921600, 512000, 460800, 256000, 115200
monitor_filters = esp32_exception_decoder, send_on_enter, log2file

build_flags = 
    -D MONITOR_SPEED=${this.monitor_speed}
    -fdiagnostics-color=always

debug_build_flags = -Os # optimize for size

lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps = 
    knolleary/PubSubClient@^2.8
    madhephaestus/ESP32Servo@^3.1.3
    bblanchon/ArduinoJson@^7.4.3
    ;itkindaworks/Metro